

# udpate all setting
upAll: upZshConfig upSublimePreferences

# zsh config
upZshConfig:
	cp ~/.zshrc ~/packages/github.com/fqncom/configuration/zsh --remove-destination

# sublime preferences setting
upSublimePreferences:
	cp ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/*.*settings ~/packages/github.com/fqncom/configuration/sublime/ --remove-destination

# link file to repo
linkFile:
	# ln -s ~/packages/github.com/fqncom/configuration/zsh/.zshrc ~/.zshrc
